### ISSUE TITLE
Error 403: disallowed_useragent on Google Auth Page in Android App

### ISSUE THREAD

**Issue by ycv005** [j0j00/flutter_user_agent#11]
For example- if I am getting a user agent- `'Mozilla/5.0 (Linux; Android 10; RMX1851 Build/QKQ1.190918.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.138 Mobile Safari/537.36';
`
Then using it in [webview plugin](https://pub.dev/packages/flutter_webview_plugin), for page of Google Oauth(it must required some user agent), google is giving is error `Error 403: disallowed_useragent` .

Temporary Solution I found is that- when I replace `; wv` with `` (blank string) in the user agent, it is working (this idea came by seeing- other user agent example on web).
Resultant user_agent- `Mozilla/5.0 (Linux; Android 10; RMX1851 Build/QKQ1.190918.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.138 Mobile Safari/537.36'`

**Comment by sam-parks** [comment]
I'm having this same issue with this user agent on iOS: 

Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by j0j00** [comment]
It sounds like this is an issue with Google specifically not allowing [webview agents](https://github.com/HoussemDellai/Google-Login-Xamarin-Forms/issues/1).

Glad you found a solution for it.

I would probably recommend reading up on the Google documentation and see if they recommend using an app specific user-agent instead of a dynamic device one as it might be needed for usage statistics purposes.
